modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="vaultfiltersruneaddon"
version="1.21.1-addon-2"
displayName="Vault Filters Rune Addon"
authors="TinoMartino094"
description='''
Addon for Vault Filters: Adds boss rune filter attributes.
'''

[[dependencies.vaultfiltersruneaddon]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vaultfiltersruneaddon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vaultfiltersruneaddon]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.f,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.vaultfiltersruneaddon]]
    modId="vaultfilters"
    mandatory=true
    versionRange="[1.21.0,)"
    ordering="AFTER"
    side="BOTH"


